version: 1.0.{build}
image: Visual Studio 2017


before_build:
- cmd: >-
    nuget restore ./src/ChoETL/ChoETL.sln

    choco install opencover.portable

    choco install codecov
build:
  project: /src/ChoETL/ChoETL.sln
  verbosity: normal
test_script:
- cmd: >-
    OpenCover.Console.exe -register:administrator -target:"nunit3-console.exe" -targetargs:"%APPVEYOR_BUILD_FOLDER%\src\Test\ChoCSVReaderTest\bin\Debug\ChoCSVReaderTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoCSVFileDiff\bin\Debug\ChoCSVFileDiff.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoCSVReaderUnitTest\bin\Debug\ChoCSVReaderUnitTest.dll %APPVEYOR_BUILD_FOLDER%\src\Test\ChoCSVSqlDbImportSample\bin\Debug\ChoCSVSqlDbImportSample.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoCSVWriterTest\bin\Debug\ChoCSVWriterTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoFixedLengthReaderTest\bin\Debug\ChoFixedLengthReaderTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoFixedLengthWriterTest\bin\Debug\ChoFixedLengthWriterTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoJSONReaderTest\bin\Debug\ChoJSONReaderTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoJSONWriterTest\bin\Debug\ChoJSONWriterTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoKVPReaderTest\bin\Debug\ChoKVPReaderTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoManifoldReaderTest\bin\Debug\ChoManifoldReaderTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoManifoldWriterTest\bin\Debug\ChoManifoldWriterTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoXmlReaderTest\bin\Debug\ChoXmlReaderTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoXmlToCSVConverterTest\bin\Debug\ChoXmlToCSVConverterTest.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoXmlToCSVSample\bin\Debug\ChoXmlToCSVSample.exe %APPVEYOR_BUILD_FOLDER%\src\Test\ChoXmlWriterTest\bin\Debug\ChoXmlWriterTest.exe" -filter:"+[*]* -[*Test]*" -output:"coverage.xml"

      
