version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: >-
    nuget restore ./src/ChoETL/ChoETL.sln

    choco install opencover.portable

    choco install codecov
build:
  project: /src/ChoETL/ChoETL.sln
  verbosity: minimal
test_script:
- cmd: >-
    OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"C:\projects\choetl\src\Test\ChoCSVReaderTest\bin\Debug\ChoCSVReaderTest.exe C:\projects\choetl\src\Test\ChoCSVReaderUnitTest\bin\Debug\ChoCSVReaderUnitTest.dll C:\projects\choetl\src\Test\ChoXmlReaderUnitTest\bin\Debug\ChoXmlReaderUnitTest.dll" -output:"coverage.xml"
after_test:
- ps: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"